version: '3.8'

services:
  service:
    build: ./planvel-backend
    container_name: planvel-service
    ports:
      - "8082:8080"
    volumes:
      - ./uploads:/uploads
    networks:
      - planvel-network

  nginx-service:
    build: ./planvel-user-frontend
    container_name: planvel-nginx-service
    ports:
      - "8083:80"   # 서비스 사용자 접근 포트
    volumes:
      - ./nginx/service.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/usr/share/nginx/uploads
    networks:
      - planvel-network


networks:
  planvel-network:
    external: true

