services:
  admin-frontend:
    build: ./planvel-admin-frontend
    ports:
      - "3000:80"
    depends_on:
      - admin


  #user-frontend:
    #build: ./planvel-user-frontend
    #ports:
    #  - "3002:80"
    #depends_on:
    #  - user

  admin:
    build: ./planvel-admin
    ports: 
      - "8080:8080"
    volumes:
      - ./uploads:/uploads

  user:
    build: ./planvel-backend
    ports:
      - "8082:8080"
    volumes:
      - ./uploads:/uploads
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./uploads:/usr/share/nginx/html/uploads
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  mysql:
    image: mysql:8.0
    container_name: planvel-mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: planvel_db
      MYSQL_USER: planvel
      MYSQL_PASSWORD: planvel1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: