version: '3.8'

services:
  service-api:
    build: ./planvel-backend
    container_name: planvel-service-api
    ports:
      - "8082:8080"
    networks:
      - planvel-network

  nginx-service:
    image: nginx:latest
    container_name: planvel-nginx-service
    ports:
      - "8083:80"   # 서비스 사용자 접근 포트
    volumes:
      - ./service-frontend:/usr/share/nginx/html    # HTML, JS, CSS만 있는 폴더
      - ./nginx/service.conf:/etc/nginx/conf.d/default.conf
    networks:
      - planvel-network


networks:
  planvel-network:
    external: true