services:
  mysql:
    image: mysql:8.0
    container_name: planvel-mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: planvel_db
      MYSQL_USER: planvel
      MYSQL_PASSWORD: planvel1234
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - planvel-network 

volumes:
  mysql_data:


networks:
  planvel-network:
    name: planvel-network
    driver: bridge